---
title: "Descriptive Analysis - afterCOVID19 "
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting up 
```{r}
library(tidyverse)
library(DT)
library(apaTables)
library(janitor)
library(knitr)
library(ggplot2)
library(wesanderson)
library(patchwork)
library(Hmisc)
library(xtable)
```

## Loading data 
```{r}
data <- read.csv(here::here("data","Mid-TN-STEM-Hub-afterCOVID19.csv"))
```

### How many teachers?
```{r}
data %>% 
    filter(Finished == "TRUE") %>%
    count() 
    
```

### What are teachers' roles?
Note: Some teachers have multiple role
```{r}
data %>% 
    select(Q15_1:Q15_8) %>%
    pivot_longer(Q15_1:Q15_8, values_to = "ROLE") %>%
    select(ROLE) %>%
    drop_na() %>%
    filter(ROLE != "") %>%
    tabyl(ROLE) %>%
    arrange(desc(n)) %>%
    adorn_pct_formatting(digits = 2) %>%
    adorn_totals(c("row")) %>%
    kable()
```

Other roles
```{r}
data %>%
    select(Q15_8_TEXT) %>%
    drop_na() %>% 
    filter(Q15_8_TEXT != '') %>%
    distinct(Q15_8_TEXT) %>%
    dplyr::rename("Other Teacher Roles" = Q15_8_TEXT) %>%
    kable()
```

### Teaching grades
Note: Some teachers teach multiple grades
```{r}
 data %>% 
    select(Q16_1:Q16_17) %>%
    mutate_all(as.character) %>%
    pivot_longer(Q16_1:Q16_17, values_to = "GRADE") %>%
    select(GRADE) %>% 
    drop_na() %>%
    filter(GRADE != '') %>%
    group_by(GRADE) %>%
    count() %>%
    ggplot(aes(x = factor(GRADE, levels = c("PreK/K", as.character(1:12))), 
               y=n)) +
    geom_bar(aes(fill=GRADE), stat = 'identity') +
    geom_text(aes(label=paste0(n), y=n + 0.25 )) +
    coord_flip() +
    scale_fill_manual(values=wes_palette(n=13, name="Darjeeling2", type ="continuous")) +
    labs(
    title = "Grades taught",
    subtitle = "Note: Many teachers teach multiple grades"
    )+
    theme_classic()+
    theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y =element_blank()
  ) 
```

### Overall satisfactory
```{r}
data %>% 
    select(SATISFIED) %>%
    group_by(SATISFIED) %>%
    count() %>% 
    ungroup() %>%
    mutate(pct = prop.table(n)) %>%
    ggplot(aes(x= factor(SATISFIED, levels = c("Very satisfied", "Satisfied","Somewhat satisfied", "Not satisfied")), 
               y=pct)) +
    geom_bar(aes(fill=SATISFIED), stat = 'identity') + 
    geom_text(aes(label=paste0(round(pct*100, digits = 2),"%")), vjust=-0.5) +
    scale_y_continuous(labels = scales::percent_format(), limits=c(0,1))+
    scale_fill_manual(values=wes_palette(n=4, name="Darjeeling2", type ="continuous")) +
    labs(
    title = "Overall satisfactory"
    )+
    theme_classic()+
    theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y =element_blank()
  ) -> overall_satisfactory_viz
```
### Technology
```{r}
data %>%
  select(TECH) %>%
  group_by(TECH) %>%
  count() %>%
  ungroup() %>%
  mutate(pct=prop.table(n)) %>%
  ggplot(aes(x= factor(TECH, levels = c("Extremely well", "Fairly well","Neither well nor poorly")), 
               y=pct)) +
  geom_bar(aes(fill=TECH), stat = 'identity') + 
  geom_text(aes(label=paste0(round(pct*100, digits = 2),"%")), vjust=-0.5) +
  scale_y_continuous(labels = scales::percent_format(), limits=c(0,1))+
  scale_x_discrete(labels = str_wrap(c("Extremely well", "Fairly well","Neither well nor poorly"), width = 15)) +
  scale_fill_manual(values=wes_palette(n=4, name="Darjeeling2", type ="continuous")) +
  labs(
    title = "Technology satisfactory"
    )+
  theme_classic()+
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y =element_blank()
  ) -> Tech_viz
```
### Information
```{r}
data %>%
  select(INFOR) %>%
  group_by(INFOR) %>%
  count() %>% 
  ungroup() %>%
  mutate(pct = prop.table(n)) %>%
  ggplot(aes(x= factor(INFOR, levels = c("All the information", "Most of the information","Some of the information", "A little of the information")), 
               y=pct)) +
  geom_bar(aes(fill=INFOR), stat = 'identity') + 
  geom_text(aes(label=paste0(round(pct*100, digits = 2),"%")), vjust=-0.5) +
  scale_y_continuous(labels = scales::percent_format(), limits=c(0,1))+
  scale_x_discrete(labels = str_wrap(c("All the information", "Most of the information","Some of the information", "A little of the information"), width = 10)) +
  scale_fill_manual(values=wes_palette(n=4, name="Darjeeling2", type ="continuous")) +
  labs(
    title = "Information satisfactory"
    )+
    theme_classic()+
    theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.title.y =element_blank()
  ) -> infor_viz
  

```

```{r}
overall_satisfactory_viz / (infor_viz + Tech_viz)
```