---
title: "matrix-visualize-afterCOVID19"
author: "Ha Bui"
date: "7/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(likert)
library(xtable)
library(sjPlot)
library(HH)
library(data.table)
library(wesanderson)
library(here)
library(knitr)
```

### Loading data
```{r}
raw <- read.csv(here::here("data", "Mid-TN-STEM-Hub-afterCOVID19.csv")) %>%
    filter(Finished == TRUE)
``` 

### Gathering columns
```{r}
data <- raw %>%
    dplyr::select(AGREE_1:AGREE_6) %>%
    gather(measure, response) 
```

### Creating the contingency table
```{r}
contingencytable <- table(data$measure, data$response) %>% as.data.frame.matrix() 

# Reorder columns
contingencytable <- contingencytable %>% 
    data.table::setcolorder(c("Strongly disagree",
                              "Disagree",
                              "Neither agree nor disagree",
                              "Agree",
                              "Strongly agree"))

# Changing row name
rownames(contingencytable) <- c("The workshop was an \neffective use of my time",
                    "The workshop was understand-\nable, clear, and professional" ,
                    "The workshop leaders \nwere knowledgeable",
                    "The workshop was relevant \nto my professional context",
                    "The workshop addressed \na need I have as an educator",
                    "The workshop will help me to \nimprove my professional practice")

# adding rownames to columns
contingencytable <- tibble::rownames_to_column(contingencytable, var = "Measure")


```


### Visualization
```{r}

likert(Measure ~ ., data=contingencytable, ylab=NULL,
       ReferenceZero=3, as.percent=TRUE,
       positive.order=FALSE, 
       main = list("Returning to School After COVID-19 Worksop Evaluation",x=unit(.5, "npc")), 
       sub= list("Agreement level",x=unit(.5, "npc")), 
       xlim=c(-10,0,20,40,60,80,100))
```